// Test data for development and testing
export const TEST_WALLET_ADDRESS = '0x54e41cc9934746AE1a9D0EcdCBb93AfC3974D4B7';

// Mock portfolio data for testing
export const MOCK_PORTFOLIO_DATA = {
  address: TEST_WALLET_ADDRESS,
  chain: 'multi-chain',
  tokens: [
    {
      id: 'eth-native-0',
      name: 'Ethereum',
      symbol: 'ETH',
      balance: 1.5,
      price: 2500,
      value: 3750,
      change24h: 2.5,
      chain: 'Ethereum',
      chainId: 'eth-mainnet',
      logo: 'https://cryptologos.cc/logos/ethereum-eth-logo.png',
      decimals: 18,
      contractAddress: '0x0000000000000000000000000000000000000000',
      riskScore: 85,
      isNative: true,
    },
    {
      id: 'usdc-0x1-1',
      name: 'USD Coin',
      symbol: 'USDC',
      balance: 1000,
      price: 1,
      value: 1000,
      change24h: 0.1,
      chain: 'Ethereum',
      chainId: 'eth-mainnet',
      logo: 'https://cryptologos.cc/logos/usd-coin-usdc-logo.png',
      decimals: 6,
      contractAddress: '0xA0b86a33E6441b8c4C8C0C8C0C8C0C8C0C8C0C8C',
      riskScore: 90,
      isNative: false,
    },
    {
      id: 'bnb-native-2',
      name: 'BNB',
      symbol: 'BNB',
      balance: 5,
      price: 300,
      value: 1500,
      change24h: -1.2,
      chain: 'BSC',
      chainId: 'bsc-mainnet',
      logo: 'https://cryptologos.cc/logos/bnb-bnb-logo.png',
      decimals: 18,
      contractAddress: '0x0000000000000000000000000000000000000000',
      riskScore: 80,
      isNative: true,
    },
    {
      id: 'link-0x2-3',
      name: 'Chainlink',
      symbol: 'LINK',
      balance: 0.5,
      price: 7.2,
      value: 3.6,
      change24h: 1.8,
      chain: 'Ethereum',
      chainId: 'eth-mainnet',
      logo: 'https://cryptologos.cc/logos/chainlink-link-logo.png',
      decimals: 18,
      contractAddress: '0x514910771AF9Ca656af840dff83E8264EcF986CA',
      riskScore: 75,
      isNative: false,
    },
    {
      id: 'uni-0x3-4',
      name: 'Uniswap',
      symbol: 'UNI',
      balance: 0.3,
      price: 6.5,
      value: 1.95,
      change24h: -0.5,
      chain: 'Ethereum',
      chainId: 'eth-mainnet',
      logo: 'https://cryptologos.cc/logos/uniswap-uni-logo.png',
      decimals: 18,
      contractAddress: '0x1f9840a85d5aF5bf1D1762F925BDADdC4201F984',
      riskScore: 70,
      isNative: false,
    },
    {
      id: 'cake-0x4-5',
      name: 'PancakeSwap Token',
      symbol: 'CAKE',
      balance: 2.1,
      price: 1.8,
      value: 3.78,
      change24h: 2.1,
      chain: 'BSC',
      chainId: 'bsc-mainnet',
      logo: 'https://cryptologos.cc/logos/pancakeswap-cake-logo.png',
      decimals: 18,
      contractAddress: '0x0E09FaBB73Bd3Ade0a17ECC321fD13a19e81cE82',
      riskScore: 65,
      isNative: false,
    },
  ],
  totalValue: 6259.33,
  change24h: 127.5,
  change24hPercent: 2.08,
  lastUpdated: new Date().toISOString(),
};

// Mock DeFi opportunities
export const MOCK_DEFI_OPPORTUNITIES = [
  {
    id: 'lido-ETH',
    name: 'Lido',
    apy: 4.2,
    asset: 'ETH',
    risk: 'Low' as const,
    protocol: 'lido',
    minAmount: 0.1,
    lockPeriod: 'No lock',
    description: 'Stake ETH and earn rewards while maintaining liquidity',
    isAvailable: true,
  },
  {
    id: 'compound-USDC',
    name: 'Compound',
    apy: 6.8,
    asset: 'USDC',
    risk: 'Low' as const,
    protocol: 'compound',
    minAmount: 100,
    lockPeriod: 'No lock',
    description: 'Lend and borrow crypto assets with competitive rates',
    isAvailable: true,
  },
  {
    id: 'pancakeswap-BNB',
    name: 'PancakeSwap',
    apy: 8.7,
    asset: 'BNB',
    risk: 'Medium' as const,
    protocol: 'pancakeswap',
    minAmount: 0.1,
    lockPeriod: 'No lock',
    description: 'BSC-based DEX with farming and staking opportunities',
    isAvailable: true,
  },
];

// Mock analytics data
export const MOCK_ANALYTICS = {
  totalValue: 6259.33,
  change24h: 127.5,
  change7d: 355,
  change30d: 1210,
  bestPerformer: MOCK_PORTFOLIO_DATA.tokens[0],
  worstPerformer: MOCK_PORTFOLIO_DATA.tokens[4],
  riskScore: 78,
  diversification: 85,
  topHoldings: MOCK_PORTFOLIO_DATA.tokens.slice(0, 3),
};
